app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => ['web']], function () {
    //
});

Route::group(['middleware' => 'web'], function () {
    Route::get('/', 'CatalogsController@index');
    Route::get('/catalogs', 'CatalogsController@index');
    Route::auth();
    Route::get('/home', 'HomeController@index');
    Route::get('/home/orders', 'HomeController@viewOrders');
    Route::resource('categories', 'CategoriesController');
    Route::resource('products', 'ProductsController');
    Route::resource('orders', 'OrdersController', ['only' => [
        'index', 'edit', 'update'
    ]]);

    Route::post('cart', 'CartController@addProduct');
    Route::get('cart', 'CartController@show');
    Route::delete('cart/{product_id}', 'CartController@removeProduct');
    Route::put('cart/{product_id}', 'CartController@changeQuantity');

    Route::get('checkout/login', 'CheckoutController@login');
    Route::post('checkout/login', 'CheckoutController@postLogin');
    Route::get('checkout/address', 'CheckoutController@address');
    Route::post('checkout/address', 'CheckoutController@postAddress');
    Route::get('checkout/payment', 'CheckoutController@payment');
    Route::post('checkout/payment', 'CheckoutController@postPayment');
    Route::get('checkout/success', 'CheckoutController@success');
});


Route::group(['middleware' => 'api'], function () {
    Route::get('address/regencies', 'AddressController@regencies');
});

app/category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['title', 'parent_id'];

    public static function boot()
    {
        parent::boot();

        static::deleting(function($model) {
            // remove parent from this category's child
            foreach ($model->childs as $child) {
                $child->parent_id = '';
                $child->save();
            }
            // remove relations to products
            $model->products()->detach();
        });
    }

    public function childs()
    {
        return $this->hasMany('App\Category', 'parent_id');
    }

    public function parent()
    {
        return $this->belongsTo('App\Category', 'parent_id');
    }

    public function products()
    {
        return $this->belongsToMany('App\Product');
    }

    /**
     * Search for category without parent
     */
    public function scopeNoParent($query)
    {
        return $this->where('parent_id', '');
    }

    /**
     * Get all product id from active category and its child
     */
    public function getRelatedProductsIdAttribute()
    {
        $result = $this->products->lists('id')->toArray();
        foreach ($this->childs as $child) {
            $result = array_merge($result, $child->related_products_id);
        }
        return $result;
    }

    /**
     * Get total amount of product from current category and its child
     * @return int
     */
    public function getTotalProductsAttribute()
    {
        return Product::whereIn('id', $this->related_products_id)->count();
    }

    public function hasParent()
    {
        return $this->parent_id > 0;
    }

    public function hasChild()
    {
        return $this->childs()->count() > 0;
    }

}

app/Http/Controllers/CatalogsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Product;
use App\Category;

class CatalogsController extends Controller
{
    public function index(Request $request)
    {
        $q = $request->get('q');
        if ($request->has('cat')) {
            $cat = $request->get('cat');
            $category = Category::findOrFail($cat);
            // we use this to get product from current category and its child
            $products = Product::whereIn('id', $category->related_products_id)
                ->where('name', 'LIKE', '%'.$q.'%');
        } else {
            $products = Product::where('name', 'LIKE', '%'.$q.'%');
        }

        if ($request->has('sort')) {
            $sort = $request->get('sort');
            $order = $request->has('order') ? $request->get('order') : 'asc';
            $field = in_array($sort, ['price', 'name']) ? $request->get('sort') : 'price';
            $products = $products->orderBy($field, $order);
        }

        $products = $products->paginate(4);

        return view('catalogs.index', compact('products', 'q', 'cat',
            'category', 'sort', 'order'));
    }
}

resources/views/catalogs/_add-product-form.blade.php
<p>
  {!! Form::open(['url' => 'cart', 'method'=>'post', 'class'=>'form-inline']) !!}
      {!! Form::hidden('product_id', $product->id) !!}

      <div class="form-group">
        {!! Form::number('quantity', null, ['class'=>'form-control', 'min' => 1, 'placeholder' => 'Jumlah order']) !!}
      </div>

    {!! Form::submit('Tambah ke Cart', ['class'=>'btn btn-primary']) !!}
  {!! Form::close() !!}
</p>

resources/views/catalogs/_breadcrumb.blade.php
<ol class="breadcrumb">
  @if(!is_null($current_category))
    <li>Kategori: <a href="{{ url('/catalogs?cat=' . $current_category->id) }}">{{ $current_category->title }}</a></li>
  @else
    <li>Kategori: Semua Produk</a></li>
  @endif
  <span class="pull-right">Urutkan Harga:
  <a href="{{ appendQueryString(['sort'=>'price', 'order'=>'asc']) }}"
    class="btn btn-default btn-xs
    {{ isQueryStringEqual(['sort'=>'price', 'order'=>'asc']) ? 'active' : ''}}"
    >Termurah</a> |
  <a href="{{ appendQueryString(['sort'=>'price', 'order'=>'desc']) }}"
    class="btn btn-default btn-xs
    {{ isQueryStringEqual(['sort'=>'price', 'order'=>'desc']) ? 'active' : ''}}"
    >Termahal</a>
</ol>

resources/views/catalogs/_category-panel.blade.php
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Lihat per kategori</h3>
  </div>
  <div class="list-group">
    <a href="/catalogs" class="list-group-item">Semua produk <span class="badge">{{ App\Product::count() }}</span></a>
    @foreach(App\Category::noParent()->get() as $category)
      <a href="{{ url('/catalogs?cat=' . $category->id)}}" class="list-group-item">{{ $category->title }}
      {!! $category->total_products > 0 ? '<span class="badge">' . $category->total_products . '</span>' : '' !!}</a>
    @endforeach
  </div>
</div>

resources/views/catalogs/_product-added.blade.php
<script>
$(document).ready(function() {
  swal({
     title: "Sukses",
     text: "Berhasil menambahkan <strong>{{ $product_name }}</strong> ke cart!",
     type: "success",
     showCancelButton: true,
     confirmButtonColor: "#63BC81",
     confirmButtonText: "Konfirmasi pesanan",
     cancelButtonText: "Lanjutkan belanja",
     html: true
  }, function(isConfirm) {
      if (isConfirm) {
          window.location = '/cart';
      }
  });
});
</script>

resources/views/catalogs/_product-thumbnail.blade.php
<h3>{{ $product->name }}</h3>
<div class="thumbnail">
  <img src="{{ $product->photo_path }}" class="img-rounded">
    <p>Model: {{ $product->model }}</p>
    <p>Harga: <strong>Rp{{ number_format($product->price, 2) }}</strong></p>
    <p>Category:
      @foreach ($product->categories as $category)
        <span class="label label-primary">
        <i class="fa fa-btn fa-tags"></i>
        {{ $category->title }}</span>
      @endforeach
    </p>

    @include('layouts._customer-feature', ['partial_view'=>'catalogs._add-product-form', 'data' => compact('product')])

</div>

resources/views/catalogs/_search-panel.blade.php
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Cari produk</h3>
  </div>
  <div class="panel-body">
    {!! Form::open(['url' => 'catalogs', 'method'=>'get']) !!}
        <div class="form-group {!! $errors->has('q') ? 'has-error' : '' !!}">
          {!! Form::label('q', 'Apa yang kamu cari?') !!}
          {!! Form::text('q', $q, ['class'=>'form-control']) !!}
          {!! $errors->first('q', '<p class="help-block">:message</p>') !!}
        </div>

        {!! Form::hidden('cat', $cat) !!}

      {!! Form::submit('Cari', ['class'=>'btn btn-primary']) !!}
    {!! Form::close() !!}
  </div>
</div>

resources/views/catalogs/_sub-category-panel.blade.php
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Subkategori untuk {{ $current_category->title }}</h3>
  </div>
  <div class="list-group">
    @foreach($current_category->childs as $category)
      <a href="{{ url('/catalogs?cat=' . $category->id)}}" class="list-group-item">{{ $category->title }}
      {!! $category->total_products > 0 ? '<span class="badge">' . $category->total_products . '</span>' : '' !!}</a>
    @endforeach
  </div>
</div>

resources/views/catalogs/index.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        @include('catalogs._search-panel', [
          'q' => isset($q) ? $q : null,
          'cat' => isset($cat) ? $cat : ''
        ])

        @include('catalogs._category-panel')

        @if (isset($category) && $category->hasChild())
          @include('catalogs._sub-category-panel', ['current_category' => $category])
        @endif

        @if (isset($category) && $category->hasParent())
          @include('catalogs._sub-category-panel', [
            'current_category' => $category->parent
          ])
        @endif

      </div>
      <div class="col-md-9">
        <div class="row">
          <div class="col-md-12">

            @include('catalogs._breadcrumb', [
              'current_category' => isset($category) ? $category : null
            ])

            @if ($errors->has('quantity'))
              <div class="alert alert-danger">
                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                  {{ $errors->first('quantity') }}
              </div>
            @endif

          </div>
          @forelse ($products as $product)
            <div class="col-md-6">
              @include('catalogs._product-thumbnail', ['product' => $product])
            </div>
          @empty
            <div class="col-md-12 text-center">
              @if (isset($q))
                <h1>:(</h1>
                <p>Produk dengan kata kunci tidak ditemukan.</p>
                @if (isset($category))
                  <p><a href="{{ url('/catalogs?q=' . $q) }}">Cari di semua kategori <i class="fa fa-arrow-right"></i></a></p>
                @endif
              @else
                <h1>:|</h1>
                <p>Belum ada produk untuk kategori ini.</p>
              @endif
              <p><a href="{{ url('/catalogs') }}">Lihat semua produk <i class="fa fa-arrow-right"></i></a></p>
            </div>
          @endforelse

          <div class="pull-right">
            {!! $products->appends(compact('cat', 'q', 'sort', 'order'))->links() !!}
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection