app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => ['web']], function () {
    //
});

Route::group(['middleware' => 'web'], function () {
    Route::get('/', 'CatalogsController@index');
    Route::get('/catalogs', 'CatalogsController@index');
    Route::auth();
    Route::get('/home', 'HomeController@index');
    Route::get('/home/orders', 'HomeController@viewOrders');
    Route::resource('categories', 'CategoriesController');
    Route::resource('products', 'ProductsController');
    Route::resource('orders', 'OrdersController', ['only' => [
        'index', 'edit', 'update'
    ]]);

    Route::post('cart', 'CartController@addProduct');
    Route::get('cart', 'CartController@show');
    Route::delete('cart/{product_id}', 'CartController@removeProduct');
    Route::put('cart/{product_id}', 'CartController@changeQuantity');

    Route::get('checkout/login', 'CheckoutController@login');
    Route::post('checkout/login', 'CheckoutController@postLogin');
    Route::get('checkout/address', 'CheckoutController@address');
    Route::post('checkout/address', 'CheckoutController@postAddress');
    Route::get('checkout/payment', 'CheckoutController@payment');
    Route::post('checkout/payment', 'CheckoutController@postPayment');
    Route::get('checkout/success', 'CheckoutController@success');
});


Route::group(['middleware' => 'api'], function () {
    Route::get('address/regencies', 'AddressController@regencies');
});

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    protected $fillable = ['id', 'user_id', 'address_id', 'bank', 'sender',
        'status', 'total_payment'];

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function details()
    {
        return $this->hasMany('App\OrderDetail');
    }

    public function address()
    {
        return $this->belongsTo('App\Address');
    }

    public function refreshTotalPayment()
    {
        $total_payment = 0;
        foreach($this->details as $detail) {
            $total_payment += $detail->total_price;
        }
        $this->total_payment = $total_payment;
        $this->save();
    }
    
    public function getPaddedIdAttribute()
    {
        return str_pad($this->id, 6, 0, STR_PAD_LEFT);
    }
    
    public static function statusList()
    {
        return [
            'waiting-payment' => 'Menunggu Pembayaran',
            'packaging' => 'Order disiapkan',
            'sent' => 'Paket dikirim',
            'finished' => 'Paket diterima'
        ];
    }

    public static function allowedStatus()
    {
        return array_keys(static::statusList());
    }

    public function getHumanStatusAttribute()
    {
        return static::statusList()[$this->status];
    }
}

resources/views/customer/view-orders.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        {!! Form::open(['url' => 'home/orders', 'method'=>'get', 'class'=>'form-inline']) !!}
            <div class="form-group {!! $errors->has('q') ? 'has-error' : '' !!}">
              {!! Form::text('q', isset($q) ? $q : null, ['class'=>'form-control', 'placeholder' => 'Order ID']) !!}
              {!! $errors->first('q', '<p class="help-block">:message</p>') !!}
            </div>

            <div class="form-group {!! $errors->has('status') ? 'has-error' : '' !!}">
              {!! Form::select('status', [''=>'Semua status']+App\Order::statusList(), isset($status) ? $status : null, ['class'=>'form-control']) !!}
              {!! $errors->first('status', '<p class="help-block">:message</p>') !!}
            </div>

          {!! Form::submit('Cari', ['class'=>'btn btn-primary']) !!}
        {!! Form::close() !!}
        <table class="table">
          <thead>
            <tr>
              <td>Order #</td>
              <td>Tanggal Order</td>
              <td>Status</td>
              <td>Pembayaran</td>
              <td>Detail</td>
            </tr>
          </thead>
          <tbody>
            @forelse($orders as $order)
            <tr>
              <td>{{ $order->padded_id }}</td>
              <td>{{ $order->created_at }}</td>
              <td>{{ $order->human_status }}</td>
              <td>
                Total: <strong>{{ number_format($order->total_payment) }} </strong><br>
                Transfer ke : {{ config('bank-accounts')[$order->bank]['bank'] }} a.n {{ config('bank-accounts')[$order->bank]['name'] }} {{ config('bank-accounts')[$order->bank]['number'] }}<br>
                Dari : {{ $order->sender }}
              </td>
              <td>
                @include('orders._details', compact('order'))
              </td>
            </tr>
            @empty
              <tr>
                <td colspan="4">Tidak ada order yang ditemukan</td>
              </tr>
            @endforelse
          </tbody>
        </table>
        {!! $orders->appends(compact('q', 'status'))->links() !!}
      </div>
    </div>
  </div>
@endsection